# Generated by Django 5.2.17 on 2026-09-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('EXPERT_TEACHER', 'Expert Teacher / Examiner'), ('RESEARCHER_ADMIN', 'Researcher Admin')], default='STUDENT', max_length=20)),
                ('assigned_arm', models.CharField(choices=[('REASONING_VISIBLE', 'Treatment: Reasoning-Visible'), ('ANSWER_ONLY', 'Control: Answer-Only')], default='REASONING_VISIBLE', max_length=20)),
                ('preferred_language', models.CharField(choices=[('bn', 'Bangla'), ('en', 'English')], default='bn', max_length=5)),
                ('grade', models.CharField(default='11', max_length=10)),
                ('prior_experience', models.CharField(default='novice', max_length=50)),
                ('consent_given', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
