# Generated by Django 5.2.17 on 2026-09-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='academic_group',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='ai_tool_familiarity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='area_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='consent_version',
            field=models.CharField(default='v1', max_length=10),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='device_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='district',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='division',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='has_computer_at_home',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='hsc_batch_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='internet_access',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='languages_known',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='learning_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='medium',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='participant_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='school_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='teaching_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='weekly_study_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participantprofile',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
