# Generated by Django 5.2.17 on 2026-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_participantprofile_academic_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
