# Generated by Django 5.2.17 on 2026-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_participantprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprofile',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprofile',
            name='withdrawn_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
