# Generated by Django 5.2.17 on 2026-09-13 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('concept_mcq', 'Concept Multiple Choice'), ('code_tracing', 'Code Tracing'), ('code_writing', 'Short Code Writing')], max_length=20)),
                ('exam_type', models.CharField(choices=[('pre', 'Pre-Test'), ('post', 'Post-Test'), ('transfer', 'Transfer Test'), ('withdrawal', 'Withdrawal Task')], default='pre', max_length=20)),
                ('question', models.TextField()),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('options', models.JSONField(default=list)),
                ('keyed_answer', models.CharField(max_length=10)),
                ('curriculum_ref', models.CharField(max_length=100)),
                ('i_cvi_score', models.FloatField(default=0.85)),
                ('is_certified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=20)),
                ('score_pct', models.IntegerField()),
                ('answers', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_marks', models.IntegerField(default=85)),
                ('max_marks', models.IntegerField(default=100)),
                ('feedback_comments', models.TextField(blank=True, null=True)),
                ('is_graded', models.BooleanField(default=True)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
                ('expert_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessment.examsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment_score', models.IntegerField(default=4)),
                ('accuracy_score', models.IntegerField(default=4)),
                ('clarity_score', models.IntegerField(default=4)),
                ('difficulty_score', models.IntegerField(default=3)),
                ('answerability_score', models.IntegerField(default=4)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expert_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessment.assessmentitem')),
            ],
        ),
    ]
