# Generated by Django 5.2.17 on 2026-09-14 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrating',
            name='item_key',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='expertrating',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='assessment.assessmentitem'),
        ),
        migrations.AddConstraint(
            model_name='expertgrade',
            constraint=models.UniqueConstraint(fields=('submission', 'expert_user'), name='uniq_grade_per_expert_submission'),
        ),
        migrations.AddConstraint(
            model_name='expertrating',
            constraint=models.UniqueConstraint(fields=('expert_user', 'item_key'), name='uniq_rating_per_expert_item'),
        ),
    ]
