# Generated by Django 5.2.17 on 2026-09-15 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_expertrating_item_key_alter_expertrating_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsubmission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='examsubmission',
            index=models.Index(fields=['student', 'exam_type', 'submitted_at'], name='submission_student_exam_idx'),
        ),
    ]
