# Generated by Django 5.2.17 on 2026-09-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_examsubmission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='grading_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('grading', 'Grading'), ('graded', 'Graded'), ('failed', 'Failed')], db_index=True, default='graded', max_length=10),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='score_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
