# Generated by Django 5.2.17 on 2026-09-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_papersitting'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
