# Generated by Django 5.2.17 on 2026-09-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('language', models.CharField(default='bn', max_length=5)),
                ('content', models.TextField()),
                ('source_ref', models.CharField(max_length=100)),
                ('chroma_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
