# Generated by Django 5.2.17 on 2026-09-17 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='running', max_length=10)),
                ('stage', models.CharField(blank=True, default='', max_length=80)),
                ('trigger', models.CharField(choices=[('api', 'Researcher dashboard'), ('command', 'manage.py ingest_rag')], default='command', max_length=10)),
                ('documents', models.JSONField(default=list)),
                ('page_range', models.CharField(blank=True, default='', max_length=20)),
                ('ocr', models.BooleanField(default=True)),
                ('reindex', models.BooleanField(default=False)),
                ('retry_empty', models.BooleanField(default=False)),
                ('workers', models.PositiveSmallIntegerField(default=3)),
                ('done_pages', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('indexed_chunks', models.PositiveIntegerField(default=0)),
                ('relabelled_chunks', models.PositiveIntegerField(default=0)),
                ('vector_count_after', models.PositiveIntegerField(blank=True, null=True)),
                ('warnings', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('log', models.JSONField(default=list)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=80)),
                ('ocr_model', models.CharField(blank=True, default='', max_length=80)),
                ('code_commit', models.CharField(blank=True, default='', max_length=40)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingest_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OcrPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(db_index=True, max_length=100)),
                ('page', models.PositiveIntegerField()),
                ('chars', models.PositiveIntegerField(default=0)),
                ('thin', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('chapter', models.CharField(blank=True, default='', max_length=100)),
                ('indexed_chunks', models.PositiveSmallIntegerField(default=0)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='curriculum.ingestrun')),
            ],
            options={
                'ordering': ['document', 'page'],
                'constraints': [models.UniqueConstraint(fields=('document', 'page'), name='uniq_ocr_page_per_document')],
            },
        ),
    ]
