# Generated by Django 5.2.17 on 2026-09-15 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logging_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interactionlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='interactionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['user', '-timestamp'], name='ilog_user_recent_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['user', 'event_type'], name='ilog_user_event_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionlog',
            index=models.Index(fields=['event_type'], name='ilog_event_idx'),
        ),
    ]
